services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - "./database:/app/database"
      - "./public/uploads:/app/public/uploads"
      - "./public/tmp:/app/public/tmp"
    environment:
      APP_BASE_URL: "${APP_BASE_URL:-http://localhost:${APP_PORT:-8080}}"
      APP_MAIL_FROM: "${APP_MAIL_FROM:-camagru@example.com}"
      APP_MAIL_REPLY_TO: "${APP_MAIL_REPLY_TO:-}"
